### PR TITLE
Emit event when a day is clicked

### PR DESCRIPTION
**Pull request by mewejo**
Thanks for the great work on this project! This simple PR will emit an event each time a day is clicked, allowing the parent component to do something, for example show a list of events on that day.

### CODE REVIEW

**Comment by ManukMinasyan** [comment]
Dear @mewejo for this we have the event "choseDay".
Please follow this section.: https://github.com/ManukMinasyan/vue-functional-calendar#events

**Comment by mewejo** [comment]
Hi @ManukMinasyan - That only fires if date picked is enabled, else nothing happens. This allows to know when a date way clicked and handle it if required. Thank you for merging :)

**Comment by ManukMinasyan** [comment]
Hi @mewejo. 
Please follow this commit: https://github.com/ManukMinasyan/vue-functional-calendar/commit/b4fbafc3042dcf5a0d8cd3a3c3f8a651fd2e659c
I think it will look better.

**Comment by mewejo** [comment]
I'd argue that `dayClicked` and `choseDay` are two different events though, and having both allows the user to decide on use case

**Comment by ManukMinasyan** [comment]
@mewejo OK I understand you now. Left both.
And added to the event list: https://github.com/ManukMinasyan/vue-functional-calendar#events

Thank you.

**Pull request merged**
